#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  connection: local
  become: False
  gather_facts: True
  roles:
    - time-and-locale
    - commands
    - gcc
    - zip
    - libs
    # - firewall