---
- name: Install firewall
  become: True
  become_method: sudo
  package:
    name: "{{ packages }}"
    state: present
    update_cache: "yes"
  vars:
    packages:
      - ufw
      - iptables
      - iptables-persistent

- name: Enable firewall
  become: true
  become_method: sudo
  community.general.ufw:
    state: enabled

- name: Allow tcp ports
  become: true
  become_method: sudo
  community.general.ufw:
    rule: allow
    port: 3001:3010
    proto: tcp
    state: enabled    