# https://github.com/vog3lm/torcs-1.3.7
---
- name: Update bashrc for plib
  become: False
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: | 
      export CFLAGS='-fPIC'
      export CPPFLAGS='\$CFLAGS'
      export CXXFLAGS='\$CFLAGS'
      cd /vagrant

- name: Check if torcs directory exists
  stat:
    path: "{{ ansible_env.HOME }}/torcs"    
  register: torcs_dir

- name: Git checkout torcs
  become: False
  ansible.builtin.git:
    repo: https://github.com/fmirus/torcs-1.3.7.git
    dest: "{{ ansible_env.HOME }}/torcs"
  when: torcs_dir.stat.exists == false

- name: configure torcs-server
  become: True
  ansible.builtin.shell:
    cmd: ./configure
    chdir: "{{ ansible_env.HOME }}/torcs"

- name: make torcs-server
  become: False
  community.general.make:
    chdir: "{{ ansible_env.HOME }}/torcs"
    
- name: make install torcs-server
  become: True
  community.general.make:
    chdir: "{{ ansible_env.HOME }}/torcs"
    target: install

- name: make datainstall torcs-server
  become: True
  community.general.make:
    chdir: "{{ ansible_env.HOME }}/torcs"
    target: datainstall