---
services:
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    volumes:
      - ./config:/config
    ports:
      - 3020:3000
      - 3021:3001
    shm_size: "1gb" #optional
    restart: unless-stopped