---
- name: Enable X11 Forwarding
  lineinfile:
    path: /etc/ssh/sshd_config
    line: X11Forwarding yes

- name: Install Ubuntu Desktop
  package:
    name: "{{ packages }}"
    state: present
    update_cache: "yes"
  vars:
    packages:
    - slim    
    - xfce4 
    - virtualbox-guest-dkms 
    - virtualbox-guest-utils 
    - virtualbox-guest-x11    