---
- name: Check if zsh exists
  stat:
    path: /bin/zsh    
  register: zsh

- name: Install zsh
  become: True
  become_method: sudo
  package:
    name: zsh
    state: present
    update_cache: "yes"
  when: zsh.stat.exists == false

- name: Install zsh-autosuggestions
  become: True
  become_method: sudo
  package: 
    name: zsh-autosuggestions

- name: Make zsh the default shell
  become: True
  become_method: sudo
  shell: chsh -s $(which zsh)

- name: Activate zsh
  become: False
  shell: zsh <<EOF\n0\nEOF
