---
- name: Install OpenGL
  become: True
  become_method: sudo
  package:
    name: "{{ packages }}"
    state: present
    update_cache: "yes"
  vars:
    packages:
      - freeglut
      - freeglut-devel
      - vorbis-tools
      - xautomation
      # UBUNTU
      # - libgl1-mesa-dev
      # - libegl1-mesa-dev
      # FEDORA      
      - mesa-libglapi
      - mesa-libGL
      - libglvnd-glx
