- name: Install MariaDB on Ubuntu
  hosts: node1
  become: true
  tasks:
    - name: Update APT Package Cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: present