---
- name: Install packages that allow apt to be used over HTTPS
  become: True
  become_method: sudo
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: "yes"
  vars:
    packages:
    - apt-transport-https
    - bat
    - ca-certificates
    - curl
    - gnupg-agent
    - nano
    - net-tools
    - openssl
    - ovmf  
    - software-properties-common
  when:
    ansible_distribution in ("Ubuntu", "Linux Mint", "Pop!_OS")

- name: Install packages
  become: True
  become_method: sudo
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
    update_cache: "yes"
  vars:
    packages:
    - bat
    - ca-certificates
    - curl
    - nano
    - net-tools
    - openssl
  when:
    ansible_distribution in ("Fedora")